version: 2.1

jobs:
  build:
    #working_directory: ~/circleci-python
    docker:
      - image: "circleci/python:3.6.4"
    steps:
      - checkout
      - run: python3 main.py
  test:
    #working_directory: ~/circleci-python
    docker:
      - image: "circleci/python:3.6.4"
    steps:
      - checkout
      - run: python3 main-test.py
  deploy:
    docker:
      - image: "circleci/python:3.6.4"
    steps:
      - checkout
      - run: python3 base1.py
  cancel:
    docker:
      - image: "circleci/python:3.6.4"  # Use the appropriate Docker image for your script
    steps:
      - checkout
      - run: python3 cancellation_script.py  # Replace with the actual script name



workflows:
  build_and_test:
    jobs:
      - build
      - test:
          timeout: 180
          requires:
            - build

      - hold:
          type: approval
          requires:
            - test
      - deploy:
          requires:
            - hold
          

# Finally
