version: 2.1
orbs:
  shellcheck: circleci/shellcheck@3.1

jobs:
  build:
    #working_directory: ~/circleci-python
    docker:
      - image: "circleci/python:3.6.4"
    steps:
      - checkout
      - run: python3 main.py
  test:
    #working_directory: ~/circleci-python
    docker:
      - image: "circleci/python:3.6.4"
    steps:
      - checkout
      - run: python3 main-test.py
  deploy:
    docker:
      - image: "circleci/python:3.6.4"
    steps:
      - checkout
      - run: python3 base1.py


  shellcheck:
    docker: 
      - image: koalaman/shellcheck-alpine:stable
    steps:
      - checkout
      - shellcheck/install
      - shellcheck/check:
          exclude: SC2148,SC2038,SC2086,SC2002,SC2016,SC2004
          dir: ./cancellation_script.sh
      - run: # Replace with the actual script name
          name: Cancel build after set time
          background: true
          command: |
            cancellation_script.sh 3story00
          
workflows:
  build_and_test:
    jobs:
      - shellcheck
      - build
      - test:
          requires:
            - build

      - hold:
          timeout: 180
          type: approval
          requires:
            - test
          
      - deploy:
          requires:
            - hold