version: 2.1
orbs:
  shellcheck: circleci/shellcheck@2.0.0

jobs:
  build:
    #working_directory: ~/circleci-python
    docker:
      - image: "circleci/python:3.6.4"
    steps:
      - checkout
      - run: python3 main.py
  test:
    #working_directory: ~/circleci-python
    docker:
      - image: "circleci/python:3.6.4"
    steps:
      - checkout
      - run: python3 main-test.py
  deploy:
    docker:
      - image: "circleci/python:3.6.4"
    steps:
      - checkout
      - run: python3 base1.py

 # cancel_py:
  #  docker:
  #    - image: "circleci/python:3.6.4"  # Use the appropriate Docker image for your script
  #  steps:
  #    - checkout
  #    - run: python3 cancellation_script.py  # Replace with the actual script name


  shellcheck/check:
    docker: 
    - image: koalaman/shellcheck-alpine:stable
    steps:
      - chekout
      
      - run: # Replace with the actual script name
          name: Cancel build after set time
          background: true
          command: |
            circle_timeout.bash 300
          
workflows:
  build_and_test:
    jobs:
      - shellcheck/check
      - build
      - test:
          requires:
            - build

      - hold:
          type: approval
          requires:
            - test
      - deploy:
          requires:
            - hold

# Finally
