version: 2.1

jobs:
  build:
    #working_directory: ~/circleci-python
    docker:
      - image: "circleci/python:3.6.4"
    steps:
      - checkout
      - run: python3 main.py
  hold: # <<< A job that will require manual approval in the CircleCI web application.
    type: approval # <<< This key-value pair will set your workflow to a status of "On Hold"
  test:
    #working_directory: ~/circleci-python
    docker:
      - image: "circleci/python:3.6.4"
    steps:
      - checkout
      - run: python3 main-test.py

workflows:
  build_and_test:
    jobs:
      - build
      - test:
        requires:
            - hold
