version: 2.1
orbs:
  shellcheck: circleci/shellcheck@3.1

jobs:
  build:
    #working_directory: ~/circleci-python
    docker:
      - image: "circleci/python:3.6.4"
    steps:
      - checkout
      - run: python3 main.py
  test:
    #working_directory: ~/circleci-python
    docker:
      - image: "circleci/python:3.6.4"
    steps:
      - checkout
      - run: python3 main-test.py
  deploy:
    docker:
      - image: "circleci/python:3.6.4"
    steps:
      - checkout
      - run: python3 base1.py

 # cancel_py:
  #  docker:
  #    - image: "circleci/python:3.6.4"  # Use the appropriate Docker image for your script
  #  steps:
  #    - checkout
  #    - run: python3 cancellation_script.py  # Replace with the actual script name

  shellcheck:
    docker: 
      - image: "shellcheck:stable"
    steps:
      - checkout
      - shellcheck/install
      - shellcheck/check:
          exclude: SC2148,SC2038,SC2086,SC2002,SC2016
          dir: ./cancellation_script.sh
      - run: # Replace with the actual script name
          name: Cancel build after set time
          background: true
          command: |
            cancellation_script.sh 300
          
workflows:
  build_and_test:
    jobs:
      - shellcheck
      - build
      - test:
          requires:
            - build

      - hold:
          type: approval
          requires:
            - test
      - deploy:
          requires:
            - hold

# Finally
