version: 2.1

jobs:
  run:
    name: Check for newer workflow
    background: true
    command: |
      curl --request POST \
        --url https://circleci.com/api/v2/workflow/$CIRCLE_API_TOKEN/cancel \
        --header 'authorization: Basic REPLACE_BASIC_AUTH'
  build:
    #working_directory: ~/circleci-python
    docker:
      - image: "circleci/python:3.6.4"
    steps:
      - checkout
      - run: python3 main.py
  test:
    #working_directory: ~/circleci-python
    docker:
      - image: "circleci/python:3.6.4"
    steps:
      - checkout
      - run: python3 main-test.py
      - timeout: 60
  
  deploy:
    docker:
      - image: "circleci/python:3.6.4"
    steps:
      - checkout
      - run: python3 base1.py


workflows:
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
      - hold:
          type: approval
          requires:
            - test
      - deploy:
          when: << pipeline.parameters.test.result == 'success' >>
          requires:
            - hold
# Finally
